"""Plot action/state distribution summaries generated by summarize_dataset.py."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

import matplotlib.pyplot as plt


def load_summary(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def plot_range(summary: dict[str, Any], field: str, output: Path) -> None:
    data = summary[f"{field}_summary"]["per_dim"]
    indexes = [item["index"] for item in data]
    mins = [item["min"] for item in data]
    maxs = [item["max"] for item in data]
    means = [item["mean"] for item in data]

    fig, ax = plt.subplots(figsize=(8, 4.2), dpi=160)
    ax.vlines(indexes, mins, maxs, color="#4F46E5", linewidth=3, alpha=0.75, label="min-max")
    ax.scatter(indexes, means, color="#DC2626", s=35, zorder=3, label="mean")
    ax.set_title(f"{field.title()} per-dimension range")
    ax.set_xlabel("dimension index")
    ax.set_ylabel("value")
    ax.set_xticks(indexes)
    ax.grid(axis="y", linestyle="--", alpha=0.3)
    ax.legend()
    fig.tight_layout()
    output.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(output)
    plt.close(fig)


def plot_std(summary: dict[str, Any], field: str, output: Path) -> None:
    data = summary[f"{field}_summary"]["per_dim"]
    indexes = [item["index"] for item in data]
    stds = [item["std"] for item in data]

    fig, ax = plt.subplots(figsize=(8, 4.2), dpi=160)
    ax.bar(indexes, stds, color="#0F766E")
    ax.set_title(f"{field.title()} per-dimension std")
    ax.set_xlabel("dimension index")
    ax.set_ylabel("std")
    ax.set_xticks(indexes)
    ax.grid(axis="y", linestyle="--", alpha=0.3)
    fig.tight_layout()
    output.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(output)
    plt.close(fig)


def main() -> None:
    parser = argparse.ArgumentParser(description="Plot action/state distribution summary.")
    parser.add_argument("--input", required=True, help="Path to distribution summary JSON.")
    parser.add_argument("--output-dir", default="assets/distributions", help="Output directory.")
    args = parser.parse_args()

    summary = load_summary(Path(args.input))
    output_dir = Path(args.output_dir)

    for field in ["action", "state"]:
        plot_range(summary, field, output_dir / f"{field}_range.png")
        plot_std(summary, field, output_dir / f"{field}_std.png")

    print(f"Wrote plots to {output_dir}")


if __name__ == "__main__":
    main()
